// Generated by CoffeeScript 1.7.1
var bowerFiles, concatCSS, dir, gulp, minifyCSS, plugins;

gulp = require('gulp');

plugins = require('gulp-load-plugins')();

concatCSS = require('gulp-concat-css');

minifyCSS = require('gulp-minify-css');

bowerFiles = require('gulp-bower-files');

dir = {
  bower: 'bower_components',
  coffee: 'assets/src/coffee',
  lib: 'assets/src/lib',
  scss: 'assets/src/scss',
  img: 'assets/build/img',
  css: 'assets/build/css',
  js: 'assets/build/js',
  twig: 'views',
  php: ''
};

gulp.task('sass', function() {
  return gulp.src(dir.scss + '/*.scss').pipe(plugins.plumber()).pipe(plugins.watch()).pipe(plugins.sass({
    style: 'compressed',
    sourceComments: 'map'
  })).pipe(plugins.rename('main.min.css')).pipe(gulp.dest(dir.css)).pipe(plugins.notify('Sass compiled')).pipe(plugins.livereload());
});

gulp.task('build_styles', ['sass'], function() {
  return gulp.src(dir.lib + '/**/*.css').pipe(plugins.plumber()).pipe(plugins.watch()).pipe(minifyCSS()).pipe(plugins.rename('lib.min.css')).pipe(gulp.dest(dir.css)).pipe(plugins.notify('All styles ok')).pipe(plugins.livereload());
});

gulp.task('coffee', function() {
  return gulp.src(dir.coffee + '/*.coffee').pipe(plugins.plumber()).pipe(plugins.watch()).pipe(plugins.coffee({
    bare: true
  })).on('error', plugins.util.log).pipe(plugins.rename('main.min.js')).pipe(gulp.dest(dir.js)).pipe(plugins.notify('CoffeeScript compiled')).pipe(plugins.livereload());
});

gulp.task('bower', function() {
  return plugins.bowerFiles().pipe(plugins.uglify()).pipe(gulp.dest(dir.js)).pipe(plugins.notify('Bower rules'));
});

gulp.task('build_scripts', function() {
  return gulp.src(dir.js + '/**/**/*.js').pipe(gulp.dest(dir.js)).pipe(plugins.notify('All scripts ok')).pipe(plugins.livereload());
});

gulp.task('php', function() {
  return gulp.src(dir.php + '*.php').pipe(plugins.watch()).pipe(plugins.livereload());
});

gulp.task('twig', function() {
  return gulp.src(dir.twig + '*.twig').pipe(plugins.watch()).pipe(plugins.livereload());
});

gulp.task('default', ['coffee', 'bower', 'build_scripts']);
